import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

import axios from 'utils/axios'

type HomePageProps = {
  cities: string[]
}

const HomePage: NextPage<HomePageProps> = ({ cities }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <ul>
          {cities.map((city) => (
            <Link key={city} href={`/cities/${city}`}>
              <a>{city}</a>
            </Link>
          ))}
        </ul>
      </main>
    </div>
  )
}

export default HomePage

async function fetchCities() {
  return axios
    .get('/maps.json')
    .then((res) => res?.data)
    .catch((err) => console.log(err))
}

export async function getServerSideProps() {
  const cities = await fetchCities()

  return {
    props: {
      cities: Object.keys(cities),
    },
  }
}
